### ISSUE TITLE
howto personalize description for a specific page ?

### ISSUE THREAD

**Issue by JOduMonT** [clemdesign/grav-plugin-social-seo-metatags#1]
Hi Clement;

I wonder if it's possible to define a description for a page
example:
I'm able to specify a description for twitter by adding
```
metadata:
    'twitter:description': 'description for twitter'
```

but unable to do the same thing for <meta name="description"
I try both :
```
description: description generale
```
and
```
metadata:
    'description': 'description generale'
```

**Comment by clemdesign** [comment]
Hi jodumont,

This plugin prioritizes the [summary](https://learn.getgrav.org/content/headers#summary) as description. So, to have possibility to define description by metadata, you shall not define the summary.
But maybe it is not the best solution. However, I have to analyse and think about it for correction.

**Comment by clemdesign** [comment]
So, after analyzing, this is a bug. My previous comment is wrong. Correction is in progress ;)

**Comment by clemdesign** [comment]
Correction is done in Tag v1.1.0 df58aa4
