### ISSUE TITLE
403

### ISSUE THREAD

**Issue by B1gG** [clemdesign/grav-plugin-social-seo-metatags#11]
I am getting a 403 in the admin page when editting the setings
<img width="559" alt="Screenshot 2019-06-08 at 22 38 36" src="https://user-images.githubusercontent.com/13992414/59152563-5a5a8d00-8a3e-11e9-985c-fd51bb4fa49b.png">

**Comment by clemdesign** [comment]
I think that the root cause is from your server or installation.

This is appears for others plugins?

**Comment by B1gG** [comment]
nope, is only with that plugin, but anyway if you have an idea where to check I can investigate.
ho, also the options, like yes/no appears with the full code:
_PLUGINS.SOCIAL_SEO_METATAGS.YES / PLUGINS.SOCIAL_SEO_METATAGS.NO_
maybe it gives a hint
I am runnig Grav v1.6.9 - Admin v1.9.4

**Comment by clemdesign** [comment]
Try to reinstall the plugin.

Your issue looks like you have not all files of plugin.

**Comment by B1gG** [comment]
I am getting the same error when click Remove from the Admin.
I will try to reinstall manually

**Comment by B1gG** [comment]
no luck. all the files are present with the right permission
-rw-rw-r--  1 www-data www-data  5730 Jun  6 21:00 blueprints.yaml
-rw-rw-r--  1 www-data www-data  1519 Jun  6 21:00 CHANGELOG.md
-rw-rw-r--  1 www-data www-data  3656 Jun  6 21:00 languages.yaml
-rw-rw-r--  1 www-data www-data  1105 Jun  6 21:00 LICENSE
-rw-rw-r--  1 www-data www-data  6094 Jun  6 21:00 README.md
-rw-rw-r--  1 www-data www-data 13583 Jun  6 21:00 social-seo-metatags.php
-rw-rw-r--  1 www-data www-data   279 Jun  6 21:13 social-seo-metatags.yaml

**Comment by clemdesign** [comment]
Did you hase still options doesn't appears with the full code?
What is your language configuration in your system configuration?

**Comment by B1gG** [comment]
EN as primary and ES as alternative

**Comment by clemdesign** [comment]
I reinstall last Grav version and this plugin and works correctly with me.

I suggest you to investigate in your configuration. Because I have ot any other idea.
