### ISSUE TITLE
[Docs] Clarity on facebook setup

### ISSUE THREAD

**Issue by jleaders** [clemdesign/grav-plugin-social-seo-metatags#12]
We are instructed to add this line
```   (config.plugins['social-seo-metatags'].enabled and config.plugins['social-seo-metatags'].social_pages.pages.facebook.enabled) ? 'xmlns:og="http://ogp.me/ns#"' : '' ```
to our "base template" -- please give more information. What and where is the base template? Is it part of my theme? Can it be edited from grav, or do I need to ssh into the server install? What is the exact path of this file?

**Comment by clemdesign** [comment]
That's depends of your Grav configuration. For the most configuration, Grav use [themes](https://learn.getgrav.org/16/themes/theme-tutorial) which structure your website.
In this theme, you should have a high level template which embed the `<html>` tag. 
Your shall include this snippet here.
In the most themes, the high level template is called "base.html.twig" located to "templates\partials".

**Comment by jleaders** [comment]
Thanks for the info. It looks like it wasn't needed to be done after all.
