### ISSUE TITLE
[Bug] Reverse proxy internal port number in meta links

### ISSUE THREAD

**Issue by jleaders** [clemdesign/grav-plugin-social-seo-metatags#13]
I serve multiple sites on this server, and so I use a reverse proxy to mask the port number (nginx `proxy_pass`). Works fine, except for this plugin does this
```<meta property="og:url" content="https://blog.example.com:9093/philosophy/topic" />```
instead of
```<meta property="og:url" content="https://blog.example.com/philosophy/topic" />```
Also it adds the port to `og:image` and ```twitter:title```

(Not sure how you're building the link but in PHP there's a difference between the various $_SERVER hostname vars, some with ports, some without, make sure you use the right one)

**Comment by jleaders** [comment]
In the referenced issue I hotpatched it to strip the port

**Comment by clemdesign** [comment]
URLs of meta-tags are build with the method `url` of the class [\Grav\Common\uri](https://learn.getgrav.org/16/api#class-grav-common-uri) provided by the Grav team.

If this is a real issue for your app, you shall discuss about a solution with the Grav team.

I can't patch the plugin for this specific request.

**Comment by jleaders** [comment]
I fixed it by setting `custom_base_url` to https://example.com in user/config/system.yaml

**Comment by clemdesign** [comment]
Great!
Did you mean as in this [guide](https://learn.getgrav.org/16/advanced/change-site-url) ?
