### ISSUE TITLE
Add blog header image into getFirstImage function

### ISSUE THREAD

**Issue by jonata** [clemdesign/grav-plugin-social-seo-metatags#15]
Hi! I would like to suggest you to add some check if the page have the blog header image (`header_image_file`) before getting the image list. I have made a very dirty solution here at the getFirstImage function (at line 231 of social-seo-metatags.php), but I am sure you could make a good implementation. With this, both twitter and og tags would use the header image if present. 

Thanks for considering.

**Comment by clemdesign** [comment]
Hi, what is `header_image_file` ?! It is provided by your theme/other plugin ?! I think that this is a custom header data provided by theme or plugin.
There is possible to implement this kind of request but the used parameter name of [Headers / Frontmatter](https://learn.getgrav.org/16/content/headers#custom-page-headers) will be specific to this plugin (and maybe shared with others plugins/themes).
So, you can propose a PR of your solution for analysis and integration.

**Comment by jonata** [comment]
Hi, it's this field on "Blog Item" tab:

![Screenshot from 2020-10-07 00-39-55](https://user-images.githubusercontent.com/908065/95284979-0f20dc00-0836-11eb-853d-9aa82805e094.png)

I am not familiar with php, just python, so I just made my solution to work in my case, so I will not PR my implementation. But the idea is simple, if this field is present on header, use that image, if not, just continue and pick the first image from the array. Thank you so much for considering!

**Comment by clemdesign** [comment]
Hi @jonata, sorry for the late. 
But maybe the PR https://github.com/clemdesign/grav-plugin-social-seo-metatags/pull/18 is that you want ?

**Comment by jonata** [comment]
Hi @clemdesign , I don't think so. This PR will get a default image from plugin config and apply to the post if no image is present. What I mean is to take the `header_image_file` field of the header of the page as the main image, if present of course.

**Comment by clemdesign** [comment]
OK @jonata, so as I say in my previous comment, I think that you use a plugin that provide the tab `Blog Item`. Do you know what is this plugin ? Or can can you give me the list of plugins used in your app, related to image/picture/...?

**Comment by jonata** [comment]
You are right @clemdesign, it is from a specific theme. I am using a custom theme I made, but the default theme "Antimatter" uses that for defining the main image on [blog item template](https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/blog_item.html.twig). I understand if you think this is too specific. Maybe you could consider adding a custom setting on the plugin settings so we can set what header property should point to pages' default image.

**Comment by clemdesign** [comment]
@jonata Your request is specific, a solution can be implemented but these shall be generic as possible. 
So, I think good idea is to add possibility to add field `header_image_file`, to be compatible with Antimatter theme, but which can manage external picture url. The complexity for this task is to deal correctly with Grav internal interface.
If you can share your "dirty" solution, this snippet can maybe help for this task.

**Comment by clemdesign** [comment]
I resolve this issue in version [2.2.0](https://github.com/clemdesign/grav-plugin-social-seo-metatags/releases/tag/2.2.0).
Now, you can use the field `header_image_file` from header page chosen first.

**Comment by jonata** [comment]
Thank you so much!!
