### ISSUE TITLE
Hyphens are missing from description

### ISSUE THREAD

**Issue by CherryDT** [clemdesign/grav-plugin-social-seo-metatags#16]
For example, a page with summary "SAN JOSE — Jonny Brodzinki is riding high on a huge wave of goals. He powered the San Jose Barracuda with two goals in a **5-1** convincing victory over the Iowa Wild on Wednesday evening at SAP Center." gets displayed as "SAN JOSE — Jonny Brodzinki is riding high on a huge wave of goals. He powered the San Jose Barracuda with two goals in a **51** convincing victory over the Iowa Wild on Wednesday evening at SAP Center." in Facebook and Twitter.

Of course, a "51 convincing victory" doesn't make a lot of sense.

It seems that the `sanitizeMarkdowns` function is causing this problem.

**Comment by CherryDT** [comment]
See #17 for fix

**Comment by clemdesign** [comment]
I did a little bit modification to manage ul and ol correctly. This version should be works for your issue.
