### ISSUE TITLE
Facebook link preview fails with og tags set and gzip off

### ISSUE THREAD

**Issue by zaszlo** [clemdesign/grav-plugin-social-seo-metatags#2]
On this grav site: http://istenieroforras.igehirdetes.ma/ the og image tag, etc. seems to be set right, gzip compression is disabled as it can be seen also from https://checkgzipcompression.com/?url=http%3A%2F%2Fistenieroforras.igehirdetes.ma%2F.

Why facebook won’t load any image for any of this site’s pages? No title, no images, nothing. What is wrong with this site? Tried to debug it with facebook’s tool, waited for weeks to change, these didn’t help.

**Comment by clemdesign** [comment]
Hi, 
Try to enable gzip compression as described [here](https://github.com/clemdesign/grav-plugin-social-seo-metatags#gzip-activation).
By.

**Comment by zaszlo** [comment]
yes, for some reason I thought gzip is causing the trouble... Working.
