### ISSUE TITLE
Using header_image_file property does not generate a valid (full) URL in meta tag

### ISSUE THREAD

**Issue by jonata** [clemdesign/grav-plugin-social-seo-metatags#20]
Thanks for implementing the `header_image_file`. However, the URL is not being set correctly. It just take the file name from the header. It should point to a full URL (`https://domain.tdl/......custom_image_header.jpg`) in order to be valid.

Thanks for considering

**Comment by clemdesign** [comment]
I changed the strategy to build path. So, if this update is not compatible with your application, I can't do more without the good interface of `header_image_file`.
Update available in [version 2.2.1](https://github.com/clemdesign/grav-plugin-social-seo-metatags/releases/tag/2.2.1)
