### ISSUE TITLE
Feature Request : Can you please also add Breadcrumb Support

### ISSUE THREAD

**Issue by ramesh-dada** [clemdesign/grav-plugin-social-seo-metatags#23]
I know there is a plugin already available but it is not working in my case, and If you will make this plugin like Yoast SEO in wordpress then this plugin will be like a full seo kit. THANKS For such a great plugin.

**Comment by clemdesign** [comment]
I will try to add it as soon.

**Comment by clemdesign** [comment]
Feature added in new release 3.0.0 in beta test.
