### ISSUE TITLE
Using cached images

### ISSUE THREAD

**Issue by jonata** [clemdesign/grav-plugin-social-seo-metatags#24]
Hi. Would it be possible to add an option to use cached images on the `og:image` and `twitter:image`? For example, I got it replacing 

`$image->url()`

with 

`$image->cache()->url()`

Thanks for considering.

**Comment by clemdesign** [comment]
Hi @jonata ,
In same way, could you propose a PR of implementation please ?
Otherwise, I will consider your issue when I have time to do it.

**Comment by clemdesign** [comment]
Feature added in new release 3.0.0.
