### ISSUE TITLE
With header_image_file, plugin still gets the first image

### ISSUE THREAD

**Issue by jonata** [clemdesign/grav-plugin-social-seo-metatags#25]
Hi. As you closed the later issue, I need to open this new one with the same title. I know you didn't like my PR after you asked to see it. As I said, not a PHP dev. Anyway, I find out a better way to fix this. In this line:

https://github.com/clemdesign/grav-plugin-social-seo-metatags/blob/9ff6086e896aa0c43d4143d3faed5d311d0b74bc/social-seo-metatags.php#L251

use this:

`$antimatterFile = $page->path() . '/' . $page->header()->header_image_file;`

That would fix the issue. Thanks for considering.

**Comment by clemdesign** [comment]
Hi @jonata , could you propose a PR with your new implementation please? 
Otherwise, I will consider your request when I have time to do it.
