### ISSUE TITLE
Feature Request: "NoArchive, NoODP" as option setting in drop-down

### ISSUE THREAD

**Issue by jeffmcneill** [clemdesign/grav-plugin-social-seo-metatags#4]
NoArchive and NoODP can each be selected, but not together, in the drop-down list for the default. Adding this combined option would be useful.

**Comment by clemdesign** [comment]
Hi, this option is added in release [1.1.2](https://github.com/clemdesign/grav-plugin-social-seo-metatags/releases/tag/1.1.2).
Thanks.
