### ISSUE TITLE
Twitter: double @

### ISSUE THREAD

**Issue by ntopulos** [clemdesign/grav-plugin-social-seo-metatags#8]
In the plugin's admin tab `Twitter Cards`, the `Username` placeholder is `@`, suggesting to put the username in the format `@username`.

However, using this format results in a double `@` in the metatag :

    <meta name="twitter:site" property="twitter:site" content="@@username" />

**Comment by clemdesign** [comment]
Twitter `Username` is identified by `@`. I understand your statement but in the current way, plugin need only 'Username` (without identificator).

I keep your suggestion in order to improve it for the next version.

**Comment by clemdesign** [comment]
This issue is fixed in release [2.0.0](https://github.com/clemdesign/grav-plugin-social-seo-metatags/releases/tag/2.0.0)
